spring:
  datasource:
    url: jdbc:h2:~/H2DB/demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: 'druid.stat.mergeSql: true;druid.stat.slowSqlMillis: '
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
    test-while-idle: true
    validation-query: SELECT 1
    test-on-borrow: true
    maxIdle: 60
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: test@qq.com
    # 授权码
    password: test

  data:
    rest:
      base-path: /api
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080